select * from CUSTOMER;

--INNER JOIN = JOIN

SELECT FIRST_NAME, LAST_NAME,ADDRESS,PHONE
FROM CUSTOMER JOIN ADDRESS
                   ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

--LEFT OUTER JOIN = LEFT JOIN

SELECT FIRST_NAME, LAST_NAME, ADDRESS,PHONE
FROM  CUSTOMER C LEFT JOIN ADDRESS A
                           ON C.ADDRESS_ID = A.ADDRESS_ID;

--RIGHT OUTER JOIN = RIGHT JOIN

SELECT FIRST_NAME, LAST_NAME, ADDRESS,PHONE
FROM  CUSTOMER C RIGHT OUTER JOIN ADDRESS A
                                  ON C.ADDRESS_ID = A.ADDRESS_ID;

--FULL JOIN
SELECT FIRST_NAME,LAST_NAME,ADDRESS,PHONE
FROM ADDRESS A FULL JOIN CUSTOMER C
                         ON C.ADDRESS_ID = A.ADDRESS_ID;

SELECT EMPLOYEE_ID, FIRST_NAME,LAST_NAME,MANAGER_ID FROM EMPLOYEES;

--SELF JOIN

SELECT WORKERS.EMPLOYEE_ID, WORKERS.FIRST_NAME, WORKERS.LAST_NAME,MANAGERS.FIRST_NAME, MANAGERS.LAST_NAME
FROM EMPLOYEES WORKERS JOIN EMPLOYEES MANAGERS
                            ON WORKERS.MANAGER_ID = MANAGERS.EMPLOYEE_ID
WHERE WORKERS.EMPLOYEE_ID<110
ORDER BY WORKERS.EMPLOYEE_ID;


























