SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID FROM EMPLOYEES;

--Who is the Neena manager ?

SELECT WORKERS.EMPLOYEE_ID,WORKERS.FIRST_NAME,WORKERS.LAST_NAME,WORKERS.MANAGER_ID,MANAGERS.EMPLOYEE_ID,MANAGERS.FIRST_NAME,MANAGERS.LAST_NAME
FROM EMPLOYEES WORKERS JOIN EMPLOYEES MANAGERS
ON WORKERS.MANAGER_ID = MANAGERS.EMPLOYEE_ID;

--how can I see all employees even if they dont have any manager ?
SELECT WORKERS.EMPLOYEE_ID,WORKERS.FIRST_NAME,WORKERS.LAST_NAME,WORKERS.MANAGER_ID,MANAGERS.EMPLOYEE_ID,MANAGERS.FIRST_NAME,MANAGERS.LAST_NAME
FROM EMPLOYEES WORKERS LEFT JOIN EMPLOYEES MANAGERS
ON WORKERS.MANAGER_ID = MANAGERS.EMPLOYEE_ID
ORDER BY 1 ASC;

SELECT W.EMPLOYEE_ID,W.FIRST_NAME,W.LAST_NAME,W.MANAGER_ID,M.EMPLOYEE_ID,M.FIRST_NAME,M.LAST_NAME
FROM EMPLOYEES W LEFT JOIN EMPLOYEES M
                                 ON W.MANAGER_ID = M.EMPLOYEE_ID
ORDER BY 1 ASC;