--1.Display all first_name and  related department_name
SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME,E.DEPARTMENT_ID,DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--Order the list based on firstname asc
SELECT FIRST_NAME,E.DEPARTMENT_ID,DEPARTMENT_NAME
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY FIRST_NAME ASC;

--2.Display all first_name and department_name including the  employee without department
SELECT FIRST_NAME,E.DEPARTMENT_ID,DEPARTMENT_NAME
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT FIRST_NAME,E.DEPARTMENT_ID,DEPARTMENT_NAME
FROM DEPARTMENTS D RIGHT JOIN EMPLOYEES E on D.DEPARTMENT_ID = E.DEPARTMENT_ID

--3.Display all first_name and department_name including the department without employee

SELECT * FROM DEPARTMENTS;

SELECT FIRST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES E RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--4.How many employee we hae for each department name
SELECT DEPARTMENT_NAME,COUNT(*)
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

--5.Display all firstname and department name including the department without employees
-- and also employees without the department

SELECT FIRST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES E FULL JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
--6.Display all cities and related country names
 SELECT * FROM LOCATIONS;
 SELECT * FROM COUNTRIES;

SELECT CITY,COUNTRY_NAME
FROM LOCATIONS INNER JOIN COUNTRIES C
on LOCATIONS.COUNTRY_ID = C.COUNTRY_ID;

--7.Display all cities and related country names including with countries without city.

SELECT CITY,COUNTRY_NAME
FROM LOCATIONS RIGHT JOIN COUNTRIES C
  on LOCATIONS.COUNTRY_ID = C.COUNTRY_ID;

--8.Display all department name and related street address

SELECT DEPARTMENT_NAME,D.LOCATION_ID,L.LOCATION_ID,STREET_ADDRESS
FROM DEPARTMENTS D JOIN LOCATIONS L
on D.LOCATION_ID = L.LOCATION_ID;

--9.Display first_name,last_name and department_name, city for all employees
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME,CITY
FROM EMPLOYEES JOIN DEPARTMENTS D ON EMPLOYEES.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L on D.LOCATION_ID = L.LOCATION_ID;

--9.Display first_name,last_name and department_name, city,country_name for all employees
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME,CITY,COUNTRY_NAME,REGION_NAME
FROM EMPLOYEES JOIN DEPARTMENTS D ON EMPLOYEES.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L on D.LOCATION_ID = L.LOCATION_ID
JOIN COUNTRIES C on L.COUNTRY_ID = C.COUNTRY_ID
JOIN REGIONS R ON C.REGION_ID = R.REGION_ID;

--how many employees working for each country_name ?
SELECT COUNTRY_NAME,COUNT(*)
FROM EMPLOYEES JOIN DEPARTMENTS D ON EMPLOYEES.DEPARTMENT_ID = D.DEPARTMENT_ID
               JOIN LOCATIONS L on D.LOCATION_ID = L.LOCATION_ID
               JOIN COUNTRIES C on L.COUNTRY_ID = C.COUNTRY_ID
GROUP BY COUNTRY_NAME
HAVING COUNT(*) >10;